{% set name = "mosec" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58440f9bf73d90b90ffa3016ffc95bb6800a285df47a8ff68bdb26d669832d07

build:
  number: 0
  skip: true  # [win]
  script:
    - export CARGO_PROFILE_RELEASE_STRIP=symbols  # [unix]
    - export RUSTFLAGS="$CARGO_BUILD_RUSTFLAGS"   # [unix]
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output LICENSES.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2                         # [build_platform != target_platform]
    - cargo-bundle-licenses
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=1,<2
  run:
    - python

test:
  imports:
    - mosec
  requires:
    - pip
  commands:
    - pip check
    - python -c "from mosec import Server, Worker"

about:
  home: https://github.com/mosecorg/mosec
  summary: Model Serving made Efficient in the Cloud
  description: |
    A high-performance serving framework for ML models, offers dynamic batching and
    multi-stage pipeline to fully exploit your compute machine.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSES.yml
  doc_url: https://mosecorg.github.io/mosec/
  dev_url: https://github.com/mosecorg/mosec

extra:
  recipe-maintainers:
    - kemingy
