{% set name = "mosec" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d65993830cdc87ac97aee4455146cddd20b88ccaac8488e3ad46e81cab0d6b78

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<37]

requirements:
  build:
    - python
    - make
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - mosec
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mosecorg/mosec
  summary: Model Serving made Efficient in the Cloud
  description: |
    A high-performance serving framework for ML models, offers dynamic batching and
    multi-stage pipeline to fully exploit your compute machine.
  license: Apache-2.0
  license_family: Apache
  license_file: license.json
  doc_url: https://mosecorg.github.io/mosec/
  dev_url: https://github.com/mosecorg/mosec

extra:
  recipe-maintainers:
    - kemingy
