bot:
  automerge: true
  check_solvable: true
build_platform:
    linux_64: linux_64
    linux_ppc64le: linux_ppc64le
    linux_aarch64: linux_aarch64
    osx_64: osx_64
    osx_arm64: osx_arm64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
